
name: docs
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.13"
      - name: Install dependencies
        run: pipx install hatch
      - name: Build
        run: hatch build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: uv run mkdocs gh-deploy --force
